import matplotlib
matplotlib.use('Agg')

# display this chapter's showpiece (generated by the last cell of this notebook)
import os
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

showpiece_path = "../assets/outputs/ch16_showpiece.png"
if os.path.exists(showpiece_path):
    image = mpimg.imread(showpiece_path)
    plt.figure(figsize=(9, 9))
    plt.imshow(image)
    plt.axis("off")
    plt.show()
else:
    print("Not generated yet -- run the whole notebook once and come back.")

# one walker, the whole idea: wander until you touch the seed, then freeze
import numpy as np

rng = np.random.default_rng(5)
moves = [(1, 0), (-1, 0), (0, 1), (0, -1)]   # down, up, right, left
seed_row, seed_col = 0, 0                    # the frozen seed, at the origin
row, col = 12, 0                             # the walker starts out in the cold
path = [(row, col)]
while abs(row - seed_row) + abs(col - seed_col) > 1:   # not yet touching
    dr, dc = moves[rng.integers(0, 4)]
    row, col = row + dr, col + dc
    path.append((row, col))

path = np.array(path)
fig, ax = plt.subplots(figsize=(7, 7))
ax.plot(path[:, 1], path[:, 0], lw=0.8, color="#5E8BC0", alpha=0.8)
ax.plot(seed_col, seed_row, "s", color="#16324F", markersize=12)
ax.plot(path[0, 1], path[0, 0], "o", color="#D96C3F")
ax.plot(path[-1, 1], path[-1, 0], "s", color="#7FA8D9", markersize=8)
ax.set_aspect("equal")
ax.axis("off")
plt.show()
print(f"{len(path)} steps from birth (orange) to freezing (pale blue, beside the seed)")

# the two grids of the fast version: the frozen cells, and their landing pads
from scipy.ndimage import binary_dilation

STEPS = np.array([(0, 1), (0, -1), (1, 0), (-1, 0)])   # the four lattice moves

demo = np.zeros((9, 9), bool)
demo[4, 3:6] = True
demo[2:5, 4] = True
pads = binary_dilation(demo)     # True on every cell touching a frozen cell

fig, axes = plt.subplots(1, 2, figsize=(7, 3.6))
axes[0].imshow(demo, cmap="gray_r")
axes[0].set_title("frozen", fontsize=9, color="#6B6B6B")
axes[1].imshow(pads, cmap="gray_r")
axes[1].set_title("frozen, dilated: where a walker sticks", fontsize=9,
                  color="#6B6B6B")
for ax in axes:
    ax.axis("off")
plt.show()

# the DLA engine: spawn on the birth ring, wander, stick, repeat
def ring_spawn(rng, center, radius, m):
    angles = rng.uniform(0, 2 * np.pi, m)
    rows = np.round(center + radius * np.sin(angles)).astype(int)
    cols = np.round(center + radius * np.cos(angles)).astype(int)
    return np.column_stack([rows, cols])          # glue into an (m, 2) array

def grow_dla(grid_size=480, n_particles=10000, stickiness=1.0, crowd=4, seed=16,
             seed_cells=None):
    rng = np.random.default_rng(seed)
    center, limit = grid_size // 2, grid_size // 2 - 2
    if seed_cells is None:
        seed_cells = (np.array([center]), np.array([center]))
    occupied = np.zeros((grid_size, grid_size), bool)
    occupied[seed_cells] = True
    age = np.full((grid_size, grid_size), -1)     # -1 empty, else deposition index
    age[seed_cells] = 0
    sticky = binary_dilation(occupied)
    radius = float(np.hypot(seed_cells[0] - center, seed_cells[1] - center).max()) + 1
    walkers = ring_spawn(rng, center, radius + 5, 8)
    count = len(seed_cells[0])
    while count < n_particles and radius < limit - 6:
        wanted = int(min(3000, max(8, crowd * radius)))
        if wanted > len(walkers):
            walkers = np.vstack([walkers, ring_spawn(rng, center, radius + 5,
                                                     wanted - len(walkers))])
        walkers += STEPS[rng.integers(0, 4, len(walkers))]
        rows, cols = walkers[:, 0], walkers[:, 1]
        lost = np.hypot(rows - center, cols - center) > min(2 * radius + 20, limit)
        walkers[lost] = ring_spawn(rng, center, radius + 5, int(lost.sum()))
        rows, cols = walkers[:, 0], walkers[:, 1]
        touching = sticky[rows, cols] & ~occupied[rows, cols]
        touching &= rng.random(len(walkers)) < stickiness
        if touching.any():
            srows, scols = rows[touching], cols[touching]
            occupied[srows, scols] = True
            age[srows, scols] = count + np.arange(len(srows))
            count += len(srows)
            for dr, dc in STEPS:                  # dilate locally: 4 landing pads each
                sticky[srows + dr, scols + dc] = True
            radius = max(radius, np.hypot(srows - center, scols - center).max())
            walkers[touching] = ring_spawn(rng, center, radius + 5, int(touching.sum()))
    return age

# grow the canonical cluster and color it by age: old core, young tips
from matplotlib.colors import LinearSegmentedColormap, to_rgb

def frost_image(age, colors, background="#0C1220"):
    cmap = LinearSegmentedColormap.from_list("frost", colors)
    grown = age >= 0
    rgb = cmap(age / max(age.max(), 1))[..., :3]   # drop the alpha channel
    rgb[~grown] = to_rgb(background)
    return rgb

ICE = ["#16324F", "#3E6FA3", "#8FB8DC", "#EAF6FF"]

dendrite_age = grow_dla(grid_size=480, n_particles=10000, seed=16)
dendrite = frost_image(dendrite_age, ICE)
print(f"{(dendrite_age >= 0).sum()} particles frozen")

plt.figure(figsize=(8, 8))
plt.imshow(dendrite)
plt.axis("off")
plt.show()

# stickiness 1.0 vs 0.3: wispy dendrite vs dense moss
loose_age = grow_dla(grid_size=480, n_particles=10000, stickiness=0.3, seed=16)

fig, axes = plt.subplots(1, 2, figsize=(12, 6))
axes[0].imshow(dendrite)
axes[0].set_title("stickiness 1.0: dendrite", fontsize=9, color="#6B6B6B")
axes[1].imshow(frost_image(loose_age, ICE))
axes[1].set_title("stickiness 0.3: moss", fontsize=9, color="#6B6B6B")
for ax in axes:
    ax.axis("off")
plt.show()

# mass-radius: count particles within r, fit the log-log slope
rows, cols = np.nonzero(dendrite_age >= 0)     # coordinates of all frozen cells
dist = np.hypot(rows - 240, cols - 240)
radii = np.geomspace(5, dist.max() * 0.6, 12)  # like linspace, but multiplicative
mass = np.array([(dist <= r).sum() for r in radii])
D, offset = np.polyfit(np.log(radii), np.log(mass), 1)

fig, ax = plt.subplots(figsize=(6, 4.5))
ax.loglog(radii, mass, "o", color="#3E6FA3")
ax.loglog(radii, np.exp(offset) * radii**D, "-", color="#D96C3F",
          label=f"slope D = {D:.2f}")
ax.set_xlabel("radius r (cells)")
ax.set_ylabel("particles within r")
ax.legend()
plt.show()
print(f"measured dimension: {D:.2f}   (published DLA value: about 1.71)")

# the same organism in three costumes
MANGANESE = ["#1A1512", "#2E2620", "#4A3D30", "#6B5B45"]
EMBER = ["#3B0A0E", "#701C1C", "#A63A22", "#D96C3F"]

pieces = [
    (grow_dla(n_particles=10000, seed=7), ICE, "#0C1220", "window frost"),
    (grow_dla(n_particles=10000, stickiness=0.5, seed=3), MANGANESE, "#F2EFE9",
     "manganese fern"),
    (grow_dla(n_particles=10000, stickiness=0.25, seed=11), EMBER, "#1E1420",
     "ember moss"),
]
fig, axes = plt.subplots(1, 3, figsize=(13, 4.6))
for ax, (piece_age, colors, ground, title) in zip(axes, pieces):
    ax.imshow(frost_image(piece_age, colors, background=ground))
    ax.set_title(title, fontsize=9, color="#6B6B6B")
    ax.axis("off")
plt.show()

# save YOUR artwork: grow, dress, enlarge, replace 'yourname'
import sys
sys.path.append("..")
from agap.helpers import save_artwork, show

my_age = grow_dla(n_particles=10000, stickiness=1.0, seed=41)
my_artwork = np.kron(frost_image(my_age, ICE), np.ones((5, 5, 1)))
show(my_artwork)
saved_path = save_artwork(my_artwork, "yourname", chapter=16)

bar_rows = np.full(120, 240)             # 120 cells, all on the center row
bar_cols = np.arange(240 - 60, 240 + 60)
twig_age = grow_dla(n_particles=9000, seed_cells=(bar_rows, bar_cols), seed=16)
show(frost_image(twig_age, ICE))


# regenerate this chapter's showpiece: the great dendrite, aged in ice
showpiece_age = grow_dla(grid_size=660, n_particles=18000, seed=16)
showpiece = np.kron(frost_image(showpiece_age, ICE), np.ones((4, 4, 1)))
show(showpiece)
saved_path = save_artwork(showpiece, "showpiece", chapter=16)